// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2l_VqMB8QjSw6S8aHoa0GgL8Yz9yXMfo',
    appId: '1:809659983290:web:b809742245c64218b9e983',
    messagingSenderId: '809659983290',
    projectId: 'medstockproject',
    authDomain: 'medstockproject.firebaseapp.com',
    storageBucket: 'medstockproject.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4KiNrOOYeXpTXoMEwbWwyh8V92HLUauM',
    appId: '1:809659983290:android:1ffbaaa8ae0b2ff7b9e983',
    messagingSenderId: '809659983290',
    projectId: 'medstockproject',
    storageBucket: 'medstockproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVp609N6vyaNyLYzpjRFjFH39fRCKde_U',
    appId: '1:809659983290:ios:9d7e476e079d9c53b9e983',
    messagingSenderId: '809659983290',
    projectId: 'medstockproject',
    storageBucket: 'medstockproject.firebasestorage.app',
    iosBundleId: 'com.example.authenticationapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVp609N6vyaNyLYzpjRFjFH39fRCKde_U',
    appId: '1:809659983290:ios:9d7e476e079d9c53b9e983',
    messagingSenderId: '809659983290',
    projectId: 'medstockproject',
    storageBucket: 'medstockproject.firebasestorage.app',
    iosBundleId: 'com.example.authenticationapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2l_VqMB8QjSw6S8aHoa0GgL8Yz9yXMfo',
    appId: '1:809659983290:web:ac165ae7e2242878b9e983',
    messagingSenderId: '809659983290',
    projectId: 'medstockproject',
    authDomain: 'medstockproject.firebaseapp.com',
    storageBucket: 'medstockproject.firebasestorage.app',
  );
}
